name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      env:
        AWS_REGION: $AWS_REGION
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NTU }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NTU }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Settings Environment Variables 
      run: |
        BRANCH="${{ github.ref_name }}"
        ACTOR="${{ github.actor }}"
        
        if [ "$BRANCH" = "main" ]; then
          WORKSPACE="prod"
          BACKEND_KEY="prod_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.PROD_ALLOWED_ORIGIN}}"
        elif [ "$BRANCH" = "dev" ]; then
          WORKSPACE="dev"
          BACKEND_KEY="dev_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN}}"
        else
          WORKSPACE="sandbox-${ACTOR}"
          BACKEND_KEY="sandbox_${ACTOR}_infra_terraform.tfstate"
          ALLOWED_ORIGIN="${{ secrets.DEV_ALLOWED_ORIGIN }}"
        fi

        echo "Using Terraform workspace: $WORKSPACE"
        echo "Using Terraform backend key: $BACKEND_KEY"
        echo "using Allowed Origin: $ALLOWED_ORIGIN"

        echo "WORKSPACE=$WORKSPACE" >> $GITHUB_ENV
        echo "BACKEND_KEY=$BACKEND_KEY" >> $GITHUB_ENV
        echo "ALLOWED_ORIGIN=$ALLOWED_ORIGIN" >> $GITHUB_ENV

    - name: Terraform fmt
      run: terraform fmt -check
    
    - name: Terraform Init
      env:
        BACKEND_KEY: ${{ env.BACKEND_KEY }}
      run: |
        echo "Using Terraform backend key: $BACKEND_KEY"
        terraform init -reconfigure \
            -backend-config="bucket=$S3_BUCKET_FOR_TF_STATE_FILE" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="key=$S3_KEY_FOR_TF_STATE_FILE/$BACKEND_KEY"            
    
    - name: Terraform Validate
      run: terraform validate
    
    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
   
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
    
    # - name: Checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with:
    #     framework: terraform
        
    - name: Select or Create Workspace
      run: |
        terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE

    - name: Terraform Plan
      run: terraform plan -var "allowed_origin=$ALLOWED_ORIGIN"